version: 0.0
os: linux 
files:
  - source: /
    destination: /webapp
hooks:
  BeforeInstall:
    - location: stop_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_app.sh    
      timeout: 300
      runas: root
