version: 0.0
os: linux 
files:
  - source: /
    destination: /build
hooks:
  ApplicationStart:
    - location: start_app.sh    
      timeout: 600 # pulling gunicorn/django image takes time for the first time
      runas: root
